### PR TITLE
First drift on xpdAn class

### PR DESCRIPTION
**Pull request by chiahaoliu**
@sbillinge 
This PR contains my first, complet attempt of ``xpdAn`` framework. Code has been tested remotely inside BNL firewall.

The design of  ``xpdAn`` class follows the discussion on UC. Current implementation details are:
  1. ``xpdAn`` has an attribute called ``all_headers`` which holds all headers under certain``SAF num``
  2. ``xpdAn`` has ``list`` method that groups all headers based on sample name by default.
  3. ``xpdAn.list`` can take keyword argument to subsample all headers belong to certain  ``SAF num``
  4. ``xpdAn`` has two properties called ``current_search`` and ``current_table`` which get updated each time searching criteria are updated.
    * ``current_search`` is a list of ``databroker.Header`` object(s) from most recent search based on ``key-value`` pairs. It allows performing operation on desired headers, such as integration and visualization
    * ``current_table`` is a ``pandas.DataFrame`` object generated based ``current_search`` with columns=[key, # of headers satisfying searching criteria]
    * both properties use private attributes so user can't update without modify searching criteria

Functionalities listed in UC are not completely implemented yet, but if this framework is desired, I can keep moving on.

### CODE REVIEW

**Comment by sbillinge** [comment]
It is a little hard to know if this is the right framework without seeing it in action, but I don't see anything that alarms me too much.  We should probably just test it out a bit for usability before spending too much time polishing it.

S

**Comment by sbillinge** [comment]
btw, not sure if it is easier to test it by pulling it in, or trying it out from your fork then pulling it in if it is working ok.

We are getting to parts of the project where I am not sure what will work best so coding things up quickly and testing them, then writing tests etc. later is probably the way to go.

S

**Comment by chiahaoliu** [comment]
The code itself was tested remotely at XPD. I will talk extensively with our group members and Justin to see if this structure makes sense and if it is easy to implement with xPDFsuite

**Comment by sbillinge** [comment]
I wasn't concerned about testing the code, but whether it serves our needs
or not... I would like to also be involved in that discussion, but by all
means get feedback from others first.

On Tue, Jul 12, 2016 at 12:12 PM, Timothy Liu <notifications@github.com>
wrote:

> The code itself was tested remotely at XPD. I will talk extensively with
> our group members and Justin to see if this structure makes sense and if it
> is easy to implement with xPDFsuite
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/xpdAcq/xpdAn/pull/2#issuecomment-232097257>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AEDrUQBKpnbtjvD8eyn-v1P-oEZAc0CGks5qU7zbgaJpZM4JJ4qp>
> .
>



-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by chiahaoliu** [comment]
Sure. I had the same concern about code not serving our needs. It will be helpful to hear some feedbacks before I reach out (and possibly confuse) Justin :)

**Comment by sbillinge** [comment]
can we meet at 10 on Friday?  My office?  Would you be able to demo the
software remotely from there?  Or if easier I can sit at your diesk.

On Wed, Jul 13, 2016 at 11:17 AM, Timothy Liu <notifications@github.com>
wrote:

> Sure. I had the same concern about code not serving our needs. It will be
> helpful to hear some feedbacks before I reach out (and possibly confuse)
> Justin :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/xpdAcq/xpdAn/pull/2#issuecomment-232388413>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AEDrUT7cYTqZ6NeCUu_XegcBKOwI6wWoks5qVQGTgaJpZM4JJ4qp>
> .
>



-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by sbillinge** [comment]
best if Max can also be there and we can play around with some real
data.....

On Wed, Jul 13, 2016 at 2:05 PM, Simon Billinge <simon.billinge@gmail.com>
wrote:

> can we meet at 10 on Friday?  My office?  Would you be able to demo the
> software remotely from there?  Or if easier I can sit at your diesk.
>
> On Wed, Jul 13, 2016 at 11:17 AM, Timothy Liu <notifications@github.com>
> wrote:
>
>> Sure. I had the same concern about code not serving our needs. It will be
>> helpful to hear some feedbacks before I reach out (and possibly confuse)
>> Justin :)
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/xpdAcq/xpdAn/pull/2#issuecomment-232388413>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe/AEDrUT7cYTqZ6NeCUu_XegcBKOwI6wWoks5qVQGTgaJpZM4JJ4qp>
>> .
>>
>
>
>
> --
> Prof. Simon Billinge
> Applied Physics & Applied Mathematics
> Columbia University
> 500 West 120th Street
> Room 200 Mudd, MC 4701
> New York, NY 10027
> Tel: (212)-854-2918 (o) 851-7428 (lab)
>
> Condensed Matter Physics and Materials Science Dept.
> Brookhaven National Laboratory
> P.O. Box 5000
> Upton, NY 11973-5000
> (631)-344-5661
>
> email: sb2896 at columbia dot edu
> home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/
>



-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by chiahaoliu** [comment]
I will ask Max if he can join us and as long as we can ssh into computer, we can demo the code (I have a clone at XPD)

**Comment by chiahaoliu** [comment]
outdated, close

**Pull request closed without merging**
