### PR TITLE
Compress mask

### PR DESCRIPTION
**Pull request by CJ-Wright**
Here are the compression/decompression tools.
@chiahaoliu

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Closes #26

**Comment by chiahaoliu** [comment]
@CJ-Wright 
during your compress and reconstruction, can you at least transform into numeric array?, I think run_engine doesn't take (or ``pymongo`` which might be a worse news) boolean array.

here is the error message:

````
/Users/timothyliu/miniconda3/envs/bs_dev/lib/python3.4/site-packages/pymongo-3.3.0-py3.4-macosx-10.6-x86_64.egg/pymongo/network.py in command(sock, dbname, spec, slave_ok, is_mongos, read_preference, codec_options, check, allowable_errors, address, check_keys, listeners, max_bson_size, read_concern)
     81     request_id, msg, size = message.query(flags, ns, 0, -1, spec,
---> 82                                           None, codec_options, check_keys)
     83

InvalidDocument: Cannot encode object: array([ True,  True,  True, ...,  True,  True,  True], dtype=bool)

During handling of the above exception, another exception occurred:
````

**Comment by CJ-Wright** [comment]
@chiahaoliu I think the better option here is to transform it into a list ourselves just in case. I think that it might take a list of Trues. The problem with numeric arrays is that they don't have `~` as an operator.
Can you try list-ifying the three outputs of compress?

**Comment by chiahaoliu** [comment]
Yes, you are right. my comment about numeric array was wrong. 
I just tested with real ``mds`` and it seems to be insertable (except for the fact metadata looks very messy once it is prin) 

One last thing is now the return from header ``data``, ``indicies`` and ``indptr`` are ``list``, so can you add corresponding adaptor to your ``decompress_mask`` function? Thanks.

**Comment by CJ-Wright** [comment]
Sure! I'll try to get this in before monday.

**Comment by CJ-Wright** [comment]
@chiahaoliu I have changed the output/input for the compress/decompress and added docstrings.
This should be ready to go!

**Comment by sbillinge** [comment]
nice work, thanks guys!  The users will be happy!!!

**Pull request merged**
